default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: Goals_development


test:
  <<: *default
  database: Goals_test


production:
  <<: *default
  database: Goals_production
  username: Goals
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>
